// Enforces the commit convention documented in .github/copilot-instructions.md.
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'refactor',
        'test',
        'chore',
        'build',
        'ci',
        'perf',
        'style',
        'revert',
      ],
    ],
    // Scope stays optional; the enum only constrains scopes that are supplied.
    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'oidc',
        'api',
        'ui',
        'database',
        'credential',
        'credential-ports',
        'tenant',
        'audit',
        'connector',
        'oauth-client',
        'role-scope',
        'jobs',
        'swagger',
        'helm',
        'ci',
        'cd',
        'architecture',
        'observability',
        'openapi',
        'operation',
        'docs',
        'deps',
        'deps-dev',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
