{{- if .Values.connectorEncryption.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digital-trust-common-service.fullname" . }}-connector-encryption
type: Opaque
stringData:
  encryption-keys.json: |
    {
      "currentVersion": 1,
      "keys": {
        "1": "{{ randBytes 32 | b64dec | printf "%x" }}"
      }
    }
{{- end }}
